FROM golang:1.25-alpine

RUN addgroup -g 1001 traffik && adduser -u 1001 -S -G traffik traffik

WORKDIR /app

COPY --chown=traffik:traffik . .

RUN go mod tidy

RUN go build -o /server 

EXPOSE  8080

USER traffik

CMD ["/server"]
